### PR TITLE
Chapter 2  solutions

### PR DESCRIPTION
**Pull request by bl3ck**
I have solved chapter 2 problems. And i would like for it to be reviewed and merged.

### CODE REVIEW

**Comment by awasum** [comment]
LGTM, merging now. Good work.

**Comment by bl3ck** [comment]
Phew my first PR

**Comment by bl3ck** [comment]
Let me take on chapter 3

**Comment by awasum** [comment]
Ok

**Comment by bl3ck** [comment]
Really best way to learn is by doing.

**Pull request merged**
